# Generated by Django 2.1.5 on 2019-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('logintime', models.DateTimeField(auto_now_add=True)),
                ('lastlogintime', models.DateTimeField()),
            ],
        ),
    ]
