# Generated by Django 2.1.5 on 2019-03-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='lastlogintime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='logintime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
