# Generated by Django 2.1.5 on 2019-03-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20190313_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='lastlogintime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='logintime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
