# Generated by Django 2.1.5 on 2019-03-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20190314_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='lastlogintime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='logintime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
